# Document how to import official TRAM results. Does not download SMPL weights
# and does not compile DROID-SLAM into the PhysTwin venv.
$ErrorActionPreference = "Stop"
Set-Location (Split-Path -Parent $PSScriptRoot)

Write-Host "P2 uses TRAM, not GVHMR."
Write-Host "TRAM code is MIT at 4861c112f3c148201326680a50c9199650da6088."
Write-Host "GVHMR is non-commercial research-only, so it was not integrated."
Write-Host ""
Write-Host "This venv does not run live TRAM. Official inference needs a Linux/conda"
Write-Host "environment with DROID-SLAM, Detectron2, VIMO, and SMPL weights from the"
Write-Host "SMPL/SMPLify site. PromptHMR is research-only and is not the P2 path."
Write-Host ""
Write-Host "Clone and run TRAM separately:"
Write-Host "  git clone https://github.com/yufu-wang/tram"
Write-Host "  git -C tram checkout 4861c112f3c148201326680a50c9199650da6088"
Write-Host "  python scripts/estimate_camera.py --video <clip>"
Write-Host "  python scripts/estimate_humans.py --video <clip>"
Write-Host ""
Write-Host "The hps/*.npy files must include pred_j3d with shape (T, 24, 3) in camera space."
Write-Host "Official dumps that only have SMPL params need the SMPL layer. This adapter"
Write-Host "will not invent joints."
Write-Host ""
Write-Host "Import into the first-camera graphics world:"
Write-Host "  .\.venv\Scripts\python.exe vision\reconstruct_humans.py --tram-dir <tram>\results\<seq>"
Write-Host ""
Write-Host "Inspect the conversion fixture without TRAM:"
Write-Host "  .\.venv\Scripts\python.exe vision\reconstruct_humans.py --from-fixture"
Write-Host "  .\.venv\Scripts\python.exe vision\reconstruct_humans.py --walk-fixture --write-video results\human_fixture.mp4"
Write-Host ""
Write-Host "Optional: set PHYSTWIN_TRAM_DIR to a results/<seq> folder for the UI attach button."
